language: node_js
node_js:
  - 10

notifications:
  email: false

addons:
  ssh_known_hosts:
    - ${HOST}

cache:
  directories:
    - "node_modules"
  yarn: true

before_install:
  - sudo apt-get install -y sshpass

install:
  - cd front
  - yarn

before_script:
  - echo -e "Host ${HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - yarn build

deploy:
  provider: script
  script: "sshpass '-p ${PASSWORD}' scp -r ./dist ${USER}@${HOST}:/var/www"
  on:
    branch: master