language: node_js
node_js:
  - 10

notifications:
  email: false

addons:
  ssh_known_hosts:
    - 47.102.196.249

cache:
  directories:
    - "node_modules"
  yarn: true

before_install:
  - sudo apt-get install -y sshpass

install:
  - cd front
  - yarn

before_script:
  - echo -e "Host 47.102.196.249\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: "sshpass '-p ${PASSWORD}' scp -r ./dist root@47.102.196.249:/var/www"
  on:
    branch: master